spring:
  profiles:
    active: after_route
  application:
    name: eureka-gateway-client
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081

---
spring:
  profiles: after_route
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://httpbin.org:80
        predicates:
        - After=2021-01-23T09:31:00+08:00[Asia/Shanghai]
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka